# -*- coding: utf-8 -*-
{
    'name': 'Accounting Reports Excel',
    'version': '11.0.1.0.0',
    'summary': """Generates Excel report for Partner Ledger,General Ledger,Balance Sheet,
                Profit and Loss,Aged Partner Balance.""",
    'description': """Generates Excel reports""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': "https://cybrosys.com/",
    'category': 'Accounting',
    'depends': ['account','product_margin', 'report_xlsx'],
    'data': [
        'views/financial_report_wizard_view.xml',
        'views/financial_report_xls_view.xml',
        'views/general_ledger_report_view.xml',
        'views/general_ledger_report_wizard_view.xml',
        'views/partner_ledgerreport.xml',
        'views/report.xml',
        'wizard/account_report_general_ledger_view.xml',
        'wizard/wizard_aged_partner_report.xml',
        'views/supplier_aging_report_view.xml',
        'report/reports.xml',
    ],
    'qweb': [],
    'license': 'OPL-1',
    'price': 19.99,
    'currency': 'EUR',
    'auto_install': False,
    'demo': [],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'application': False
}
